name: build and release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-22.04
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip build
    - name: Build sdist
      run: |
        python -m build
    - name: Create Github release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "dist/*"
        token: ${{ secrets.github_token }}
